### ISSUE TITLE
Support for default branch other than 'master'

### ISSUE THREAD

**Issue by mdwhatcott** [smartystreets/gitreview#2]
Some of the (personal) repos I work with don't use the `master` branch. I intend to extend this tool to be able to work with those repos. Something like this:

```
$ git config --add review.branch <name-of-default-branch>
```

**Comment by joliver** [comment]
Looks good to me.

**Comment by mdwhatcott** [comment]
Resolved by https://github.com/smartystreets/gitreview/pull/3
